export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #fdf2f8 0%, #faf5ff 100%)",
    padding: "24px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  maxWidth: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    textAlign: "center",
    marginBottom: "32px",
  },
  headerTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "16px",
  },
  mainTitle: {
    fontSize: "2.5rem",
    fontWeight: "bold",
    color: "#1f2937",
    margin: 0,
  },
  subtitle: {
    fontSize: "1.125rem",
    color: "#6b7280",
    maxWidth: "600px",
    margin: "0 auto",
  },
  statsCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow:
      "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    padding: "24px",
    marginBottom: "32px",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "24px",
  },
  statItem: {
    textAlign: "center",
  },
  statNumber: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "8px",
  },
  statValue: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#1f2937",
  },
  statLabel: {
    color: "#6b7280",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(350px, 1fr))",
    gap: "32px",
    marginBottom: "48px",
  },
  categoryCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow:
      "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    padding: "24px",
    height: "fit-content",
  },
  categoryHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "24px",
    padding: "12px",
    borderRadius: "8px",
    color: "white",
  },
  categoryTitle: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    margin: 0,
  },
  itemCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "16px",
    marginBottom: "16px",
    transition: "box-shadow 0.2s ease",
    cursor: "pointer",
  },
  itemHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "8px",
  },
  itemName: {
    fontWeight: "600",
    color: "#1f2937",
    fontSize: "1.125rem",
    margin: 0,
  },
  rating: {
    display: "flex",
    alignItems: "center",
  },
  ratingText: {
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "#6b7280",
    marginLeft: "4px",
  },
  author: {
    fontSize: "0.875rem",
    color: "#9ca3af",
    marginBottom: "8px",
  },
  description: {
    color: "#6b7280",
    fontSize: "0.875rem",
    marginBottom: "12px",
    lineHeight: "1.4",
  },
  featuresContainer: {
    marginBottom: "12px",
  },
  featuresGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px",
  },
  featureTag: {
    background: "#f3f4f6",
    color: "#374151",
    padding: "4px 8px",
    borderRadius: "12px",
    fontSize: "0.75rem",
  },
  itemFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  price: {
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "#059669",
  },
  button: {
    background: "#ec4899",
    color: "white",
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: "500",
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  footer: {
    textAlign: "center",
  },
  footerCard: {
    background: "white",
    borderRadius: "12px",
    boxShadow:
      "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    padding: "24px",
  },
  footerTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "8px",
  },
  footerText: {
    color: "#6b7280",
    marginBottom: "16px",
  },
  footerButton: {
    background: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
    color: "white",
    padding: "12px 32px",
    borderRadius: "8px",
    fontWeight: "500",
    border: "none",
    cursor: "pointer",
    transition: "transform 0.2s ease",
  },
};

// Modal styles
export const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "2rem",
    maxWidth: "800px",
    width: "90%",
    maxHeight: "80vh",
    overflow: "auto",
    position: "relative",
    boxShadow:
      "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
  },
  closeButton: {
    position: "absolute",
    top: "1rem",
    right: "1rem",
    background: "none",
    border: "none",
    fontSize: "1.5rem",
    cursor: "pointer",
    color: "#6b7280",
    padding: "0.5rem",
  },
  modalTitle: {
    fontSize: "1.75rem",
    fontWeight: "700",
    marginBottom: "1.5rem",
    color: "#1f2937",
  },
  searchForm: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    marginBottom: "2rem",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  label: {
    fontSize: "0.875rem",
    fontWeight: "600",
    color: "#374151",
  },
  input: {
    padding: "0.75rem",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "1rem",
  },
  select: {
    padding: "0.75rem",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "1rem",
    backgroundColor: "white",
  },
  searchButton: {
    backgroundColor: "#8b5cf6",
    color: "white",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  resultsContainer: {
    marginTop: "2rem",
  },
  resultCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "1rem",
    marginBottom: "1rem",
    backgroundColor: "#f9fafb",
  },
  providerName: {
    fontSize: "1.125rem",
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "0.5rem",
  },
  providerInfo: {
    fontSize: "0.875rem",
    color: "#6b7280",
    marginBottom: "0.25rem",
  },
  loading: {
    textAlign: "center",
    padding: "2rem",
    color: "#6b7280",
  },
  error: {
    color: "#ef4444",
    padding: "1rem",
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "8px",
    marginTop: "1rem",
  },
};
